language: c
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - make
            - libglfw3 
            - libglfw3-dev
            - libfreetype6-dev 
            - libssl-dev
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - freetype
            - glfw
            - openssl
script:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
    fi
  - |
    if [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then
      git clone https://github.com/vlang/v
      cd v
      make
      cd ..
      v/v install glfw
      v/v .
    fi
