name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron:  '31 1,12 * * *'

jobs:
  code-formatting:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
        path: v
    - name: Checkout ved
      uses: actions/checkout@v2
      with:
        path: ved
    - name: Build V
      run: |
        cd v
        make
        sudo ./v symlink
    # - name: v vet
    #   run: |
    #     v vet .
    - name: v fmt -verify
      # v fmt -verify timer.v
      # v fmt -verify ved.v
      run: |
        v fmt -verify config.v
        v fmt -verify query.v
        v fmt -verify view.v

  # build:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-20.04, macos-10.15, windows-2019]
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set up latest V
  #     uses: nocturlab/setup-vlang-action@v1
  #     with:
  #       v-version: latest
  #     id: v
  #   - name: Build ved
  #     run: v -prod .
